### ISSUE TITLE
Test Program

### ISSUE THREAD

**Issue by Pixis39** [Pixis39/AIBO-Singer#11]
Create a test program so that you know you can work with AIBO programming on a basic level.

---

**Acceptance Criteria:** 
- [x] The test program functions without any bugs, and with proper transitions between movements

---

**Tasks:**

- [x] Create a basic test skit in Skitter - a song
- [x] Create a program in YART that performs the action when AIBO is praised
- [x] Test the program with Java

**Comment by Pixis39** [comment]
The test was successful! https://twitter.com/dogdisks/status/1219830609746546688?s=20
