### ISSUE TITLE
Mood Variables

### ISSUE THREAD

**Issue by Pixis39** [Pixis39/AIBO-Singer#12]
Based on what I have observed reading Dogslife's code, AIBO's mood can be controlled through variables. It should be possible to change AIBO's mood when certain things happen (increase happy by 1, decrease sad by 1, etc...), and change certain behaviors based on AIBO's mood.

---

**Acceptance Criteria:** 
- [ ] Mood changes can be observed in AIBO Singer's behavior

---

**Tasks:**

- [ ] Create mood variables (blank)
- [ ] Have certain events change mood as necessary
- [ ] Have AIBO print mood variables to memory stick
- [ ] Ensure that mood changes cause desired changes in actions

---

**Notes:**

- Be careful not to turn things into giant nested if/then statements. Keep it cool.
