### ISSUE TITLE
Table Mode

### ISSUE THREAD

**Issue by Pixis39** [Pixis39/AIBO-Singer#2]
Table mode is an integral feature of any AIBO software, naturally. I want to be sure I get this right so that users will not need to worry about their AIBO wandering about when it should be sitting still.

---

**Acceptance Criteria:** Table Mode in AIBO Singer is tested and working properly.

---

**Tasks:**

- [ ] Create table mode: hold a certain sensor for 3 seconds to enable, and AIBO will only sit or lie down, not stand up or walk away
- [ ] Confirm that table mode can be activated while using the software
- [ ] Confirm that table mode can be deactivated while using the software and AIBO returns to normal behavior afterwards
- [ ] Confirm on at least 3 separate boots that table mode does not exit on its own:
   - [ ] Test 1
   - [ ] Test 2
   - [ ] Test 3
- [ ] Have 3 different beta testers confirm that table mode does not exit on its own.
   - [ ] Beta Tester 1
   - [ ] Beta Tester 2
   - [ ] Beta Tester 3
