### ISSUE TITLE
Ball-playing

### ISSUE THREAD

**Issue by Pixis39** [Pixis39/AIBO-Singer#3]
Like any AIBO, AIBO Singer loves its pink ball and other similar objects. But because it's so strongly inclined towards being gentle and kind, AIBO Singer only pats or nuzzles them.

---

**Acceptance Criteria:** AIBO Singer exhibits the appropriate behaviors upon detecting pink objects.
---

**Tasks:**

- [ ] Confirm AIBO Singer is capable of basic ball recognition and tracking
- [ ] Create at least 2 original ball-playing skits, on top of basic imported ones
- [ ] Confirm AIBO Singer can perform the ball-playing skits properly and with no issues
