### ISSUE TITLE
Low Battery Indication

### ISSUE THREAD

**Issue by Pixis39** [Pixis39/AIBO-Singer#4]
It would be nice if AIBO Singer indicates when the battery is low and goes into the "station pose" like many standard softwares do, but I'm not sure if this is possible.

---

**Acceptance Criteria:** 
- [ ] AIBO Singer accurately indicates when the battery is low and charging is needed.

---

**Tasks:**

- [ ] Research the feasibility of this feature
- [ ] Implement low battery indication
- [ ] Confirm that low battery indication works as intended and does not over- or under-estimate battery level
