### ISSUE TITLE
Performances

### ISSUE THREAD

**Issue by Pixis39** [Pixis39/AIBO-Singer#5]
This is the big boy and AIBO Singer's main draw: performances! When asked to "sing a song", AIBO Singer lies down and the owner can ask it to sing a song from a category by pressing a specific paw switch. The categories are "happy", "sad", "exciting", and "peaceful". When told "showtime!", AIBO Singer chooses one of these songs at random to perform.

---

**Acceptance Criteria:** 
- [ ] AIBO Singer's performance mode is capable of performing songs from each category accurately when asked
- [ ] AIBO Singer's "showtime" mode performs songs from any category at random

---

**Tasks:**

- [ ] Add and confirm responses to the "sing a song" and "showtime" commands
- [ ] Responds to each paw switch being pressed differently
- [ ] Develop songs
   - [ ] "Happy" songs
      - [ ] 1
      - [ ] 2
      - [ ] 3
      - [ ] 4
   - [ ] "Sad" songs
      - [ ] 1
      - [ ] 2
      - [ ] 3
      - [ ] 4
   - [ ] "Exciting" songs
      - [ ] 1
      - [ ] 2
      - [ ] 3
      - [ ] 4
   - [ ] "Peaceful" songs
      - [ ] 1
      - [ ] 2
      - [ ] 3
      - [ ] 4
- [ ] Confirm songs play in the correct categories, and not outside of them
- [ ] Confirm that performance actions work correctly for AIBO - each song must be tested individually

---

**Notes:**

- Look into the "Bender" personality for guidance on this. "Bender" performs different skits based on how the owner moves the paws - this is very similar to what I want AIBO Singer to do.
