### ISSUE TITLE
Autonomous Pictures

### ISSUE THREAD

**Issue by Pixis39** [Pixis39/AIBO-Singer#6]
It would be nice if AIBO Singer takes autonomous pictures, but I'm not sure if this is possible.

---

**Acceptance Criteria:** 
- [ ] AIBO can take pictures when it wants to.

---

**Tasks:**

- [ ] Research feasibility of this feature
- [ ] Confirm AIBO indicates when it is taking pictures - MUST have noises to alert the owner
- [ ] Program AIBO Singer to take pictures when it wants
   - Specific picture-taking scenarios (all would only be sometimes):
   - [ ] When AIBO is very happy
   - [ ] When AIBO thinks there is a human in front of it
   - [ ] After AIBO sings to its pink ball
   - [ ] When AIBO is praised after a performance
