### ISSUE TITLE
Autonomous Behavior

### ISSUE THREAD

**Issue by Pixis39** [Pixis39/AIBO-Singer#7]
When AIBO Singer is left alone, it should do normal AIBO things. It's mostly inclined to sit around, but maybe sometimes it gets up on its own, looks for its pink ball or sings to random things it finds around the house.

---

**Acceptance Criteria:** 
- [ ] All autonomous behaviors work and can be demonstrated.
- [ ] Autonomous behaviors "feel" like other software. This is the real toughie and could make or break AIBO Singer.

---

**Tasks:**

- [ ] Confirm autonomous behaviors can be observed when AIBO is left alone
- [ ] Random skits
- [ ] Walking around
- [ ] Singing to objects
- [ ] Searching for the ball
