### ISSUE TITLE
Boot-up tasks

### ISSUE THREAD

**Issue by Pixis39** [Pixis39/AIBO-Singer#9]
When booted, AIBO Singer should have a custom boot tune, as well as perform a small "warm-up" skit after booting.

---

**Acceptance Criteria:** 
- [ ] AIBO Singer exhibits the appropriate behavior upon booting up.

---

**Tasks:**

- [ ] Create boot tune in LMMS/Audacity
- [ ] Confirm boot tune is valid and can be booted
- [ ] Create boot-up skit in Skitter
- [ ] Add skit to actions upon boot-up and confirm it plays correctly

**Comment by Pixis39** [comment]
The boot tune has been created. ZIP archive with raw .WAV file (not for AIBO usage) and original LMMS project file here:

[AIBO_Singer_Boot.zip](https://github.com/Pixis39/AIBO-Singer/files/4100811/AIBO_Singer_Boot.zip)

The .WAV made for AIBO usage will be available within the stick's files once the stick is uploaded to GitHub.

**Comment by Pixis39** [comment]
Boot-up skit has been completed but needs some fine-tuning.
